import "../env.ts";
import { prisma } from "../lib/prisma.js";

async function generateSampleData() {
  // await generateSampleContentData();
  // await generateSampleEmployeeData();
  await generateSampleAccountData();
}

async function generateSampleContentData() {
  //Content sample data
  await prisma.content.createMany({
    data: [
      {
        title: "learning rating mentor ILT powerpoint",
        url: "https://zhwxfsahkisstuxignvi.supabase.co/storage/v1/object/public/teamg-prototype/learning_rating_mentor_ILT_powerpoint.pptx",
        content_owner: "Bob Smith",
        for_position: "UNDERWRITER",
        last_modified_time: new Date("2021-06-07"),
        expiration_time: new Date("2022-06-07"),
        content_type: "WORKFLOW",
        status: "IN_USE",
      },
      {
        title: "learning foundations progress tracker spreadsheet",
        url: "https://zhwxfsahkisstuxignvi.supabase.co/storage/v1/object/public/teamg-prototype/learning_foundations_progress_tracker.xlsx",
        content_owner: "Carol Lee",
        for_position: "UNDERWRITER",
        last_modified_time: new Date("2022-06-07"),
        expiration_time: new Date("2023-06-07"),
        content_type: "WORKFLOW",
        status: "UNAVAILABLE",
      },
      {
        title: "Prc Exp Rating GL LossEligibilityTool",
        url: "https://zhwxfsahkisstuxignvi.supabase.co/storage/v1/object/public/teamg-prototype/prc_exp_rating_gl_LossEligibilityTool_11767.xls",
        content_owner: "David Kim",
        for_position: "UNDERWRITER",
        last_modified_time: new Date("2023-06-07"),
        expiration_time: new Date("2024-06-07"),
        content_type: "WORKFLOW",
        status: "AVAILABLE",
      },
      {
        title: "prc rating wksht manual earthquake",
        url: "https://zhwxfsahkisstuxignvi.supabase.co/storage/v1/object/public/teamg-prototype/prc_rating_wksht_manual_earthquake.xls",
        content_owner: "Nina Patel",
        for_position: "UNDERWRITER",
        last_modified_time: new Date("2025-01-20"),
        expiration_time: new Date("2026-01-20"),
        content_type: "REFERENCE",
        status: "AVAILABLE",
      },
      {
        title: "sys isonet CMCManual Instructions",
        url: "https://zhwxfsahkisstuxignvi.supabase.co/storage/v1/object/public/teamg-prototype/sys_isonet_CMCManual_Instructions.doc",
        content_owner: "Owen Carter",
        for_position: "UNDERWRITER",
        last_modified_time: new Date("2025-01-25"),
        expiration_time: new Date("2026-01-25"),
        content_type: "REFERENCE",
        status: "IN_USE",
      },
      {
        title: "Desktop Management Tool",
        url: "https://example.com/desktop-management-tool",
        content_owner: "Brian Lee",
        for_position: "UNDERWRITER",
        last_modified_time: new Date("2025-02-01"),
        expiration_time: new Date("2026-02-01"),
        content_type: "WORKFLOW",
        status: "AVAILABLE",
      },
      {
        title: "Property View Job Aid",
        url: "https://example.com/property-view-job-aid",
        content_owner: "Nina Patel",
        for_position: "UNDERWRITER",
        last_modified_time: new Date("2025-02-05"),
        expiration_time: new Date("2026-02-05"),
        content_type: "WORKFLOW",
        status: "AVAILABLE",
      },
      {
        title: "Underwriting Workstation SOP",
        url: "https://example.com/underwriting-workstation-sop",
        content_owner: "Owen Carter",
        for_position: "UNDERWRITER",
        last_modified_time: new Date("2025-02-10"),
        expiration_time: new Date("2026-02-10"),
        content_type: "WORKFLOW",
        status: "IN_USE",
      },
      {
        title: "Flood Eligibility Checklist",
        url: "https://example.com/flood-eligibility-checklist",
        content_owner: "Brian Lee",
        for_position: "UNDERWRITER",
        last_modified_time: new Date("2025-02-14"),
        expiration_time: new Date("2026-02-14"),
        content_type: "REFERENCE",
        status: "AVAILABLE",
      },
      {
        title: "Experience Rating Plan Overview",
        url: "https://example.com/experience-rating-plan-overview",
        content_owner: "Nina Patel",
        for_position: "UNDERWRITER",
        last_modified_time: new Date("2025-02-18"),
        expiration_time: new Date("2026-02-18"),
        content_type: "REFERENCE",
        status: "AVAILABLE",
      },
      {
        title: "ISO Net Search Tips",
        url: "https://example.com/iso-net-search-tips",
        content_owner: "Owen Carter",
        for_position: "UNDERWRITER",
        last_modified_time: new Date("2025-02-22"),
        expiration_time: new Date("2026-02-22"),
        content_type: "REFERENCE",
        status: "UNAVAILABLE",
      },
      {
        title: "State On Hold Procedures",
        url: "https://example.com/state-on-hold-procedures",
        content_owner: "Brian Lee",
        for_position: "UNDERWRITER",
        last_modified_time: new Date("2025-02-27"),
        expiration_time: new Date("2026-02-27"),
        content_type: "WORKFLOW",
        status: "AVAILABLE",
      },
      {
        title: "Coastal Risk Review Workflow",
        url: "https://example.com/coastal-risk-review-workflow",
        content_owner: "Nina Patel",
        for_position: "UNDERWRITER",
        last_modified_time: new Date("2025-03-03"),
        expiration_time: new Date("2026-03-03"),
        content_type: "WORKFLOW",
        status: "IN_USE",
      },
      {
        title: "Forms Knowledge Base",
        url: "https://example.com/forms-knowledge-base",
        content_owner: "Owen Carter",
        for_position: "UNDERWRITER",
        last_modified_time: new Date("2025-03-08"),
        expiration_time: new Date("2026-03-08"),
        content_type: "REFERENCE",
        status: "AVAILABLE",
      },
      {
        title: "Exception Referral Template",
        url: "https://example.com/exception-referral-template",
        content_owner: "Brian Lee",
        for_position: "UNDERWRITER",
        last_modified_time: new Date("2025-03-12"),
        expiration_time: new Date("2026-03-12"),
        content_type: "WORKFLOW",
        status: "AVAILABLE",
      },
      {
        title: "Compliance Update",
        url: "https://example.com/compliance",
        content_owner: "Emily Brown",
        for_position: "UNDERWRITER",
        last_modified_time: new Date("2025-06-07"),
        expiration_time: new Date("2026-06-07"),
        content_type: "REFERENCE",
        status: "IN_USE",
      },
      {
        title: "Renewal Instructions",
        url: "https://example.com/renewal",
        content_owner: "Betsy Smith",
        for_position: "BUSINESS_ANALYST",
        last_modified_time: new Date("2020-12-07"),
        expiration_time: new Date("2021-06-07"),
        content_type: "REFERENCE",
        status: "AVAILABLE",
      },
      {
        title: "Policy Guide",
        url: "https://example.com/policy",
        content_owner: "Alice Johnson",
        for_position: "BUSINESS_ANALYST",
        last_modified_time: new Date("2020-06-07"),
        expiration_time: new Date("2021-06-07"),
        content_type: "REFERENCE",
        status: "AVAILABLE",
      },
      {
        title: "Reference Guide",
        url: "https://example.com/reference-guide",
        content_owner: "Alice Johnson",
        for_position: "BUSINESS_ANALYST",
        last_modified_time: new Date("2025-03-09"),
        expiration_time: new Date("2026-03-09"),
        content_type: "REFERENCE",
        status: "AVAILABLE",
      },
      {
        title: "Testing Checklist",
        url: "https://example.com/testing-checklist",
        content_owner: "Priya Shah",
        for_position: "BUSINESS_ANALYST",
        last_modified_time: new Date("2025-03-15"),
        expiration_time: new Date("2026-03-15"),
        content_type: "WORKFLOW",
        status: "AVAILABLE",
      },
      {
        title: "Release Procedure",
        url: "https://example.com/release-procedure",
        content_owner: "Lucas Reed",
        for_position: "BUSINESS_ANALYST",
        last_modified_time: new Date("2025-03-21"),
        expiration_time: new Date("2026-03-21"),
        content_type: "WORKFLOW",
        status: "AVAILABLE",
      },
      {
        title: "Forms Update Process",
        url: "https://example.com/forms-update-process",
        content_owner: "Priya Shah",
        for_position: "BUSINESS_ANALYST",
        last_modified_time: new Date("2025-02-15"),
        expiration_time: new Date("2026-02-15"),
        content_type: "WORKFLOW",
        status: "AVAILABLE",
      },
      {
        title: "ACT User Reference Guide",
        url: "https://example.com/act-user-reference-guide",
        content_owner: "Alice Johnson",
        for_position: "BUSINESS_ANALYST",
        last_modified_time: new Date("2025-01-12"),
        expiration_time: new Date("2026-01-12"),
        content_type: "REFERENCE",
        status: "AVAILABLE",
      },
      {
        title: "PMS Entry Procedure",
        url: "https://example.com/pms-entry-procedure",
        content_owner: "Priya Shah",
        for_position: "BUSINESS_ANALYST",
        last_modified_time: new Date("2025-01-18"),
        expiration_time: new Date("2026-01-18"),
        content_type: "WORKFLOW",
        status: "AVAILABLE",
      },
      {
        title: "Kentucky Tax Exemption Job Aid",
        url: "https://example.com/kentucky-tax-exemption-job-aid",
        content_owner: "Lucas Reed",
        for_position: "BUSINESS_ANALYST",
        last_modified_time: new Date("2025-01-22"),
        expiration_time: new Date("2026-01-22"),
        content_type: "REFERENCE",
        status: "IN_USE",
      },
      {
        title: "CPP Rater Resource Site",
        url: "https://example.com/cpp-rater-resource-site",
        content_owner: "Alice Johnson",
        for_position: "BUSINESS_ANALYST",
        last_modified_time: new Date("2025-01-27"),
        expiration_time: new Date("2026-01-27"),
        content_type: "REFERENCE",
        status: "AVAILABLE",
      },
      {
        title: "Workaround Tool",
        url: "https://example.com/workaround-tool",
        content_owner: "Priya Shah",
        for_position: "BUSINESS_ANALYST",
        last_modified_time: new Date("2025-02-02"),
        expiration_time: new Date("2026-02-02"),
        content_type: "WORKFLOW",
        status: "AVAILABLE",
      },
      {
        title: "Enhancement QA Handoff Steps",
        url: "https://example.com/enhancement-qa-handoff-steps",
        content_owner: "Lucas Reed",
        for_position: "BUSINESS_ANALYST",
        last_modified_time: new Date("2025-03-04"),
        expiration_time: new Date("2026-03-04"),
        content_type: "WORKFLOW",
        status: "IN_USE",
      },
      {
        title: "Reference Guide for Analysts",
        url: "https://example.com/reference-guide-for-analysts",
        content_owner: "Alice Johnson",
        for_position: "BUSINESS_ANALYST",
        last_modified_time: new Date("2025-03-09"),
        expiration_time: new Date("2026-03-09"),
        content_type: "REFERENCE",
        status: "AVAILABLE",
      },
      {
        title: "Testing Evidence Checklist",
        url: "https://example.com/testing-evidence-checklist",
        content_owner: "Priya Shah",
        for_position: "BUSINESS_ANALYST",
        last_modified_time: new Date("2025-03-15"),
        expiration_time: new Date("2026-03-15"),
        content_type: "WORKFLOW",
        status: "AVAILABLE",
      },
      {
        title: "Release Readiness Procedure",
        url: "https://example.com/release-readiness-procedure",
        content_owner: "Lucas Reed",
        for_position: "BUSINESS_ANALYST",
        last_modified_time: new Date("2025-03-21"),
        expiration_time: new Date("2026-03-21"),
        content_type: "WORKFLOW",
        status: "AVAILABLE",
      },
    ],
  });
}

async function generateSampleEmployeeData() {
  // Employee sample data
  await prisma.employee.createMany({
    data: [
      {
        first_name: "Alice",
        last_name: "Johnson",
        date_of_birth: new Date("1995-03-12"),
        position: "BUSINESS_ANALYST",
        department: "ACCOUNTING",
        start_date: new Date("2022-06-01"),
        supervisor: "Michael Smith",
        phone_number: "401-555-1234",
        personal_email: "alice.johnson@gmail.com",
        corporate_email: "alice.johnson@company.com",
        accountUsername: "emp1",
      },
      {
        first_name: "Brian",
        last_name: "Lee",
        date_of_birth: new Date("1990-07-25"),
        position: "UNDERWRITER",
        department: "OPERATION_TECHNOLOGY",
        start_date: new Date("2021-09-15"),
        supervisor: "Sarah Davis",
        phone_number: "401-555-2345",
        personal_email: "brian.lee@yahoo.com",
        corporate_email: "brian.lee@company.com",
        accountUsername: "emp2",
      },
      {
        first_name: "Carla",
        last_name: "Martinez",
        date_of_birth: new Date("1988-11-03"),
        position: "BUSINESS_ANALYST",
        department: "ACCOUNTING",
        start_date: new Date("2020-01-20"),
        supervisor: "Michael Smith",
        phone_number: "401-555-3456",
        personal_email: "carla.martinez@gmail.com",
        corporate_email: "carla.martinez@company.com",
        accountUsername: "ba1",
      },
      {
        first_name: "David",
        last_name: "Nguyen",
        date_of_birth: new Date("1993-05-18"),
        position: "BUSINESS_ANALYST",
        department: "OPERATION_TECHNOLOGY",
        start_date: new Date("2023-02-10"),
        supervisor: "Sarah Davis",
        phone_number: "401-555-4567",
        personal_email: "david.nguyen@gmail.com",
        corporate_email: "david.nguyen@company.com",
        accountUsername: "ba2",
      },
      {
        first_name: "Emily",
        last_name: "Brown",
        date_of_birth: new Date("1997-09-30"),
        position: "UNDERWRITER",
        department: "ACCOUNTING",
        start_date: new Date("2024-07-01"),
        supervisor: "Michael Smith",
        phone_number: "401-555-5678",
        personal_email: "emily.brown@gmail.com",
        corporate_email: "emily.brown@company.com",
        accountUsername: "underwriter1",
      },
      {
        first_name: "Owen",
        last_name: "Carter",
        date_of_birth: new Date("1991-08-19"),
        position: "UNDERWRITER",
        department: "OPERATION_TECHNOLOGY",
        start_date: new Date("2020-10-12"),
        supervisor: "Sarah Davis",
        phone_number: "401-555-6790",
        personal_email: "owen.carter@gmail.com",
        corporate_email: "owen.carter@company.com",
        accountUsername: "underwriter2",
      },
      {
        first_name: "Maya",
        last_name: "Thompson",
        date_of_birth: new Date("1988-03-27"),
        position: "ADMIN",
        department: "OPERATION_TECHNOLOGY",
        start_date: new Date("2019-06-03"),
        supervisor: "Sarah Davis",
        phone_number: "401-555-2481",
        personal_email: "maya.thompson@gmail.com",
        corporate_email: "maya.thompson@company.com",
        accountUsername: "underwriter3",
      },
      {
        first_name: "Ethan",
        last_name: "Brooks",
        date_of_birth: new Date("1993-11-05"),
        position: "ADMIN",
        department: "OPERATION_TECHNOLOGY",
        start_date: new Date("2021-02-15"),
        supervisor: "Sarah Davis",
        phone_number: "401-555-9134",
        personal_email: "ethan.brooks@gmail.com",
        corporate_email: "ethan.brooks@company.com",
        accountUsername: "underwriter4",
      },
      {
        first_name: "Chloe",
        last_name: "Bennett",
        date_of_birth: new Date("1990-01-14"),
        position: "ADMIN",
        department: "OPERATION_TECHNOLOGY",
        start_date: new Date("2018-09-24"),
        supervisor: "Sarah Davis",
        phone_number: "401-555-5627",
        personal_email: "chloe.bennett@gmail.com",
        corporate_email: "chloe.bennett@company.com",
        accountUsername: "underwriter5",
      },
    ],
  });
}

async function generateSampleAccountData() {
  await prisma.account.createMany({
    data: [
      {
        employeeUuid: "007bb83d-766d-41e1-80eb-f2c5f0e15f0b",
        username: "emp1",
        password: "emp1",
        type: "EMPLOYEE",
      },
      {
        employeeUuid: "15dcabb9-4dc7-45f8-a010-3c3e77804914",
        username: "emp2",
        password: "emp2",
        type: "EMPLOYEE",
      },
      {
        employeeUuid: "e5a6e638-1b71-47ae-9632-834886f50b6f",
        username: "underwriter1",
        password: "underwriter1",
        type: "EMPLOYEE",
      },
      {
        employeeUuid: "557aab98-74d7-4613-87c7-8792290e6298",
        username: "underwriter2",
        password: "underwriter2",
        type: "EMPLOYEE",
      },
      {
        employeeUuid: "67008116-8a33-4e57-8960-981b93d50bef",
        username: "ba1",
        password: "ba1",
        type: "EMPLOYEE",
      },
      {
        employeeUuid: "7e4b2b7e-a88f-4869-8837-83cd61827d34",
        username: "ba2",
        password: "ba2",
        type: "EMPLOYEE",
      },
      {
        employeeUuid: "0b674cce-3aba-4fd0-801a-1c8f518a0bd1",
        username: "admin",
        password: "admin",
        type: "ADMIN",
      },
      {
        employeeUuid: "0da1c9d0-860a-4486-aa50-ca324fcd3d6f",
        username: "admin2",
        password: "admin2",
        type: "ADMIN",
      },
      {
        employeeUuid: "30c1a953-3456-4245-9319-5cd28ad66ea9",
        username: "admin3",
        password: "admin3",
        type: "ADMIN",
      },
    ],
  });
}

generateSampleData()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
